enabled: true
cooldown-refund:
  enabled: true
  refund-percent: 100
player-detection:
  enabled: true
  radius: 10
cooldown:
  enabled: true
  length: 5-m
observation-timer:
  enabled: true
  length: 10-s
resource-checker:
  enabled: true
  memory-time: 30-m